FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

RUN pip install -U pip
RUN pip install pipenv 

WORKDIR /app

# Copy the script into the container
COPY scoringScript.py .

# Install the required packages
RUN pip install pandas pyarrow scikit-learn requests pathlib

# Set the entrypoint to the script
ENTRYPOINT ["python", "scoringScript.py"]